version: '3'

services:
  splitstreamer:
    build: .
    image: ghcr.io/matthieucoder/splitstreamer:${TAG:-latest}
    volumes:
      - ./config.toml:/app/config.toml
      - ./waiting.webm:/app/waiting.webm
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/dri:/dev/dri"
    environment:
        GST_DEBUG: "1"
  web:
    build: web
    image: ghcr.io/matthieucoder/splitstreamer/web:${TAG:-latest}