version: '3'

services:
  server:
    build:
      context: .
      args:
        TARGET: server
    image: ghcr.io/matthieucoder/splitstreamer/server:${TAG:-latest}
  client:
    build:
      context: .
      args:
        TARGET: client
    image: ghcr.io/matthieucoder/splitstreamer/client:${TAG:-latest}
  confgen:
    build:
      context: .
      args:
        TARGET: confgen
    image: ghcr.io/matthieucoder/splitstreamer/confgen:${TAG:-latest}
  web:
    build: web
    image: ghcr.io/matthieucoder/splitstreamer/web:${TAG:-latest}